import { useState } from 'react'
import { Outlet, NavLink, useNavigate, useLocation } from 'react-router-dom'
import { UserButton, useUser } from '@clerk/react'
import {
  LayoutDashboard,
  Upload,
  List,
  HelpCircle,
  Plus,
  X,
  Zap,
  FileSpreadsheet,
  BarChart3,
  Sparkles,
  ShieldCheck,
  Search,
  ChevronRight,
  Activity,
} from 'lucide-react'
import { cn } from '@/lib/utils'

const navItems = [
  { to: '/dashboard', icon: LayoutDashboard, label: 'Dashboard' },
  { to: '/runs', icon: List, label: 'Runs' },
  { to: '/upload', icon: Upload, label: 'Upload Data' },
]

const PAGE_TITLES = {
  '/dashboard': 'Dashboard',
  '/runs': 'Reconciliation Runs',
  '/upload': 'Upload Data',
}

const INFO_SECTIONS = [
  {
    icon: FileSpreadsheet,
    color: 'text-primary bg-primary/10',
    title: 'Upload & Ingest',
    body: 'Go to Upload Data and drop in two CSVs — one for orders, one for payments. DATAClaw stores them securely, scoped entirely to your account.',
    note: 'Required: order_id, net_amount, currency, status (orders) · transaction_ref, order_reference, amount, type, status (payments)',
  },
  {
    icon: Zap,
    color: 'text-amber-500 bg-amber-500/10',
    title: 'Reconciliation Engine',
    body: 'After upload, the backend automatically runs a deterministic matching algorithm — no AI involved in matching. Every order is matched against its payment and classified into one of 11 discrepancy types.',
    note: 'Types: Amount Mismatch, Currency Mismatch, Duplicate Payment, Phantom Payment, Missing Payment, Failed Payment, Cancelled & Charged, Partial Refund, Unexpected Refund, Duplicate Order, Data Quality',
  },
  {
    icon: BarChart3,
    color: 'text-green-500 bg-green-500/10',
    title: 'Dashboard KPIs & Charts',
    body: 'The Dashboard always shows your latest run. KPIs include: Orders Processed, Payments Processed, Clean Orders Value (orders with zero issues), Discrepancies Found, Total in Dispute, and Total at Risk.',
    note: 'Charts show severity distribution (pie) and risk by discrepancy type (bar). Click View Details to jump to the Runs page.',
  },
  {
    icon: Search,
    color: 'text-violet-400 bg-violet-500/10',
    title: 'Drill-Down & Filtering',
    body: 'In the Runs page, select any past upload session to view its full discrepancy table. Filter by severity or type, search by order ID or transaction ref, and click any row to open the full detail panel.',
    note: 'Pagination supports up to 200 rows per page. Use the search bar to find specific orders or transactions instantly.',
  },
  {
    icon: Sparkles,
    color: 'text-pink-400 bg-pink-500/10',
    title: 'AI Analysis (Gemini)',
    body: 'Click "Generate Analysis" inside a discrepancy detail panel to get an AI root cause explanation, business impact assessment, urgency/confidence scores, and recommended action steps — all generated by Gemini.',
    note: 'AI Summaries for a whole run can be generated from the Runs page or Dashboard. Both are cached in the database — they are only generated once per run.',
  },
  {
    icon: ShieldCheck,
    color: 'text-blue-400 bg-blue-500/10',
    title: 'Security & Privacy',
    body: 'All data is scoped to your Clerk account. No other user can access your sessions, orders, payments, or discrepancy results. API keys are never exposed to the frontend.',
    note: 'LLM calls are made server-side only. Your financial data never leaves the backend.',
  },
]

function InfoModal({ open, onClose }) {
  if (!open) return null
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />
      {/* Panel */}
      <div className="relative z-10 w-full max-w-2xl max-h-[85vh] flex flex-col bg-card border border-border rounded-xl shadow-2xl mx-4 overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border shrink-0">
          <div className="flex items-center gap-3">
            <div className="flex size-9 items-center justify-center rounded-lg bg-primary/10">
              <HelpCircle className="size-4 text-primary" />
            </div>
            <div>
              <h2 className="text-base font-bold text-foreground">How DATAClaw Works</h2>
              <p className="text-xs text-muted-foreground">Features, tips, and what to expect</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="flex size-8 items-center justify-center rounded-md text-muted-foreground hover:text-foreground hover:bg-accent transition-colors cursor-pointer"
          >
            <X className="size-4" />
          </button>
        </div>

        {/* Scrollable content */}
        <div className="overflow-y-auto flex flex-col gap-3 p-6">
          {INFO_SECTIONS.map((section, i) => (
            <div key={i} className="flex gap-4 p-4 rounded-lg border border-border bg-muted/20 hover:bg-muted/30 transition-colors">
              <div className={cn('flex size-9 items-center justify-center rounded-lg shrink-0 mt-0.5', section.color)}>
                <section.icon className="size-4" />
              </div>
              <div className="flex flex-col gap-1 min-w-0">
                <p className="text-sm font-semibold text-foreground">{section.title}</p>
                <p className="text-xs text-muted-foreground leading-relaxed">{section.body}</p>
                {section.note && (
                  <p className="text-[10px] text-muted-foreground/70 leading-relaxed mt-1 font-mono">{section.note}</p>
                )}
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="px-6 py-3 border-t border-border bg-muted/10 shrink-0">
          <p className="text-xs text-center text-muted-foreground">
            DATAClaw · Financial reconciliation powered by deterministic matching + Gemini AI
          </p>
        </div>
      </div>
    </div>
  )
}

function SidebarLink({ to, icon: Icon, label }) {
  return (
    <NavLink
      to={to}
      className={({ isActive }) =>
        cn(
          'flex items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium transition-all duration-150 group',
          isActive
            ? 'bg-primary/10 text-primary'
            : 'text-muted-foreground hover:bg-accent hover:text-foreground'
        )
      }
    >
      {({ isActive }) => (
        <>
          <Icon className={cn('size-4 shrink-0 transition-colors', isActive ? 'text-primary' : 'text-muted-foreground group-hover:text-foreground')} />
          <span className="flex-1">{label}</span>
          {isActive && <ChevronRight className="size-3.5 text-primary opacity-60" />}
        </>
      )}
    </NavLink>
  )
}

export default function AppLayout() {
  const navigate = useNavigate()
  const location = useLocation()
  const { user } = useUser()
  const [infoOpen, setInfoOpen] = useState(false)

  const pageTitle = PAGE_TITLES[location.pathname] || 'DATAClaw'

  return (
    <>
      <div className="flex h-screen overflow-hidden bg-background">
        {/* ── Sidebar ─────────────────────────────────────────── */}
        <aside className="flex w-58 shrink-0 flex-col border-r border-border bg-card" style={{ width: '232px' }}>
          {/* Logo / Brand */}
          <div className="flex h-14 items-center gap-3 border-b border-border px-4">
            <div className="flex size-8 items-center justify-center rounded-lg bg-primary shadow-[0_0_12px_rgba(59,130,246,0.4)] overflow-hidden p-1">
              <img src="/favicon.png" alt="DATAClaw Logo" className="size-full object-contain" />
            </div>
            <div className="flex flex-col leading-none">
              <span className="text-base font-extrabold tracking-tight text-foreground">
                DATA<span className="text-primary">Claw</span>
              </span>
              <span className="text-[9px] text-muted-foreground/70 font-medium tracking-widest uppercase">Reconciliation</span>
            </div>
          </div>

          {/* Nav */}
          <nav className="flex flex-1 flex-col gap-0.5 p-3 overflow-y-auto">
            <p className="px-3 py-1.5 text-[10px] font-semibold text-muted-foreground/50 uppercase tracking-widest">Navigation</p>
            {navItems.map((item) => (
              <SidebarLink key={item.to} {...item} />
            ))}
          </nav>

          {/* User */}
          <div className="border-t border-border p-3">
            <div className="flex items-center gap-2.5 rounded-md p-2 hover:bg-accent transition-colors cursor-pointer">
              <UserButton
                appearance={{
                  elements: { avatarBox: 'size-7' },
                }}
              />
              <div className="flex-1 min-w-0">
                <p className="text-xs font-semibold text-foreground truncate">
                  {user?.firstName || user?.emailAddresses?.[0]?.emailAddress?.split('@')[0] || 'Account'}
                </p>
                <p className="text-[10px] text-muted-foreground truncate">
                  {user?.emailAddresses?.[0]?.emailAddress || ''}
                </p>
              </div>
            </div>
          </div>
        </aside>

        {/* ── Main content ────────────────────────────────────── */}
        <main className="flex flex-1 flex-col overflow-hidden relative">
          {/* Top Navbar */}
          <header className="flex h-14 shrink-0 items-center justify-between border-b border-border bg-card/50 backdrop-blur-sm px-6 sticky top-0 z-10">
            <div className="flex items-center gap-2">
              <h2 className="text-sm font-semibold text-foreground">{pageTitle}</h2>
            </div>
            <div className="flex items-center gap-2">
              <button
                onClick={() => navigate('/upload')}
                className="inline-flex items-center gap-1.5 h-8 rounded-md bg-primary px-3 text-xs font-semibold text-primary-foreground hover:bg-primary/90 transition-all shadow-sm hover:shadow-md cursor-pointer"
              >
                <Plus className="size-3.5" />
                New Run
              </button>
              <button
                onClick={() => setInfoOpen(true)}
                title="Help & Features"
                className="inline-flex items-center justify-center size-8 rounded-md border border-border bg-card text-muted-foreground hover:text-foreground hover:bg-accent transition-colors cursor-pointer"
              >
                <HelpCircle className="size-4" />
              </button>
            </div>
          </header>

          <div className="flex-1 overflow-y-auto">
            <Outlet />
          </div>
        </main>
      </div>

      {/* Info Modal */}
      <InfoModal open={infoOpen} onClose={() => setInfoOpen(false)} />
    </>
  )
}
