"""add llm_session_summaries

Revision ID: 8915d716aadb
Revises: afd9af46d822
Create Date: 2026-09-01 22:08:58.459973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8915d716aadb'
down_revision = 'afd9af46d822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_session_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('model_used', sa.String(length=60), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('total_at_risk_usd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('key_findings', sa.JSON(), nullable=True),
    sa.Column('top_priority', sa.Text(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('overall_severity', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['upload_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('llm_session_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_session_summaries_clerk_user_id'), ['clerk_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_session_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_session_summaries_clerk_user_id'))

    op.drop_table('llm_session_summaries')
    # ### end Alembic commands ###
