"""Initial migration

Revision ID: b1947a2090e6
Revises: 
Create Date: 2026-09-01 20:03:03.268947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1947a2090e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=64), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('orders_filename', sa.Text(), nullable=True),
    sa.Column('payments_filename', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('orders_count', sa.Integer(), nullable=True),
    sa.Column('payments_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_sessions_clerk_user_id'), ['clerk_user_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['upload_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_clerk_user_id'), ['clerk_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_session_id'), ['session_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_ref', sa.String(length=50), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('order_reference', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_settled', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['upload_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_clerk_user_id'), ['clerk_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_session_id'), ['session_id'], unique=False)

    op.create_table('reconciliation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=64), nullable=False),
    sa.Column('discrepancy_type', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('transaction_ref', sa.String(length=50), nullable=True),
    sa.Column('order_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('risk_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['upload_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_results_clerk_user_id'), ['clerk_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_results_session_id'), ['session_id'], unique=False)

    op.create_table('llm_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('model_used', sa.String(length=60), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('likely_cause', sa.Text(), nullable=True),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('urgency', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=True),
    sa.Column('is_partial', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['reconciliation_results.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_explanations')
    with op.batch_alter_table('reconciliation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_results_session_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_results_clerk_user_id'))

    op.drop_table('reconciliation_results')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_session_id'))
        batch_op.drop_index(batch_op.f('ix_payments_clerk_user_id'))

    op.drop_table('payments')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_session_id'))
        batch_op.drop_index(batch_op.f('ix_orders_clerk_user_id'))

    op.drop_table('orders')
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_sessions_clerk_user_id'))

    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
